/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const continueParameter: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "continueParameter"
  ],
  mapper: {
    serializedName: "continue",
    type: {
      name: "String"
    }
  }
};
export const exact: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "exact"
  ],
  mapper: {
    serializedName: "exact",
    type: {
      name: "Boolean"
    }
  }
};
export const exportParameter: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "exportParameter"
  ],
  mapper: {
    serializedName: "export",
    type: {
      name: "Boolean"
    }
  }
};
export const fieldSelector: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fieldSelector"
  ],
  mapper: {
    serializedName: "fieldSelector",
    type: {
      name: "String"
    }
  }
};
export const gracePeriodSeconds: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "gracePeriodSeconds"
  ],
  mapper: {
    serializedName: "gracePeriodSeconds",
    type: {
      name: "Number"
    }
  }
};
export const includeUninitialized: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "includeUninitialized"
  ],
  mapper: {
    serializedName: "includeUninitialized",
    type: {
      name: "Boolean"
    }
  }
};
export const labelSelector: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "labelSelector"
  ],
  mapper: {
    serializedName: "labelSelector",
    type: {
      name: "String"
    }
  }
};
export const limit: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "limit"
  ],
  mapper: {
    serializedName: "limit",
    type: {
      name: "Number"
    }
  }
};
export const name: msRest.OperationURLParameter = {
  parameterPath: "name",
  mapper: {
    required: true,
    serializedName: "name",
    constraints: {
      Pattern: /[a-z0-9][a-z0-9\-]*/
    },
    type: {
      name: "String"
    }
  }
};
export const namespace: msRest.OperationURLParameter = {
  parameterPath: "namespace",
  mapper: {
    required: true,
    serializedName: "namespace",
    constraints: {
      Pattern: /[a-z0-9][a-z0-9\-]*/
    },
    type: {
      name: "String"
    }
  }
};
export const orphanDependents: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "orphanDependents"
  ],
  mapper: {
    serializedName: "orphanDependents",
    type: {
      name: "Boolean"
    }
  }
};
export const propagationPolicy: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "propagationPolicy"
  ],
  mapper: {
    serializedName: "propagationPolicy",
    type: {
      name: "String"
    }
  }
};
export const resourceVersion: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "resourceVersion"
  ],
  mapper: {
    serializedName: "resourceVersion",
    type: {
      name: "String"
    }
  }
};
export const timeoutSeconds: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "timeoutSeconds"
  ],
  mapper: {
    serializedName: "timeoutSeconds",
    type: {
      name: "Number"
    }
  }
};
export const watch: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "watch"
  ],
  mapper: {
    serializedName: "watch",
    type: {
      name: "Boolean"
    }
  }
};
